# Generated by Django 5.2.8 on 2025-11-10 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0003_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "carbon_sequestered",
                    models.FloatField(default=0.0, help_text="In metric tons"),
                ),
                (
                    "carbon_offset",
                    models.FloatField(default=0.0, help_text="In metric tons"),
                ),
                ("species_count", models.IntegerField(default=0)),
                (
                    "vegetation_index",
                    models.FloatField(default=0.0, help_text="NDVI value 0-1"),
                ),
                ("tree_cover_percentage", models.FloatField(default=0.0)),
                (
                    "soil_quality_index",
                    models.FloatField(default=0.0, help_text="0-100 scale"),
                ),
                (
                    "water_retention",
                    models.FloatField(default=0.0, help_text="In cubic meters"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="projects.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("site", "date")},
            },
        ),
    ]
